# Generated by Django 4.2.29 on 2026-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TO_APPLY', 'To Apply'), ('SENT', 'Sent'), ('INTERVIEW', 'Interview'), ('REJECTED', 'Rejected'), ('NO_RESPONSE', 'No Response'), ('ACCEPTED', 'Accepted')], max_length=20)),
                ('next_action', models.CharField(blank=True, max_length=255, null=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
