# Generated by Django 4.2.29 on 2026-04-05 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_standard', models.CharField(max_length=100)),
                ('nom_sans_pronom', models.CharField(max_length=100)),
                ('nom_sans_accent', models.CharField(max_length=100)),
                ('nom_standard_majuscule', models.CharField(max_length=100)),
                ('reg_nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(max_length=255)),
                ('job_contract_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed term'), ('INTERNSHIP', 'Fixed term'), ('APPRENTICE_SHIP', 'Apprenticeship'), ('FREELANCE', 'Freelance'), ('OTHER', 'Other')], max_length=50)),
                ('job_mission', models.TextField(blank=True, null=True)),
                ('offer_link', models.URLField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(choices=[('TO_APPLY', 'To Apply'), ('SENT', 'Sent'), ('INTERVIEW', 'Interview'), ('REJECTED', 'Rejected'), ('NO_RESPONSE', 'No Response'), ('ACCEPTED', 'Accepted')], max_length=20)),
                ('next_action', models.CharField(choices=[('TO_FOLLOW_UP', 'To follow up'), ('TO_PREPARE_INTERVIEW', 'To prepare for the interview'), ('NONE', 'None'), ('SEND_APPLICATION', 'Send application')], default='NONE', max_length=255)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.city')),
            ],
        ),
    ]
