# Generated by Django 4.2.29 on 2026-04-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_contract_type',
            field=models.CharField(choices=[('PERMANENT', 'CDI'), ('FIXED_TERM', 'CDD'), ('INTERNSHIP', 'Stage'), ('APPRENTICE_SHIP', 'Alternance'), ('FREELANCE', 'Freelance'), ('OTHER', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='next_action',
            field=models.CharField(choices=[('TO_FOLLOW_UP', 'Relancer'), ('TO_PREPARE_INTERVIEW', "Préparer l'entretien"), ('NONE', 'Aucune'), ('Envoyé la candidature', 'Send application')], default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('TO_PREPARE', 'A préparer'), ('SENT', 'Envoyé'), ('INTERVIEW', 'Entretien'), ('REJECTED', 'Refusé'), ('NO_RESPONSE', 'Sans réponse'), ('ACCEPTED', 'Accepté')], max_length=20),
        ),
    ]
