# Generated by Django 4.2.29 on 2026-04-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_job_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_apply',
            field=models.DateField(blank=True, null=True),
        ),
    ]
