# Generated by Django 4.2.29 on 2026-04-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_date_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='next_action',
            field=models.CharField(choices=[('TO_FOLLOW_UP', 'Relancer'), ('TO_PREPARE_INTERVIEW', "Préparer l'entretien"), ('NONE', 'Aucune'), ('SEND_APPLICATION', 'Envoyer la candidature')], default='NONE', max_length=255),
        ),
    ]
